### ISSUE TITLE
arbitrary data in resweb.yaml

### ISSUE THREAD

**Issue by upachler** [upachler/resweb#3]
# Motivation #

Currently, `resweb.yaml` only allows for a specific set of keys per site. Besides `claim_rules`, only `url` and `name` are supported. A typical site may look like this:

```yaml
...
site_list:
  sites:
  - name: Disney
    url: https://www.disney.com/
    claim_rules:
    - path: 'realm_access.roles'
      operator: ContainsMatch
      operand:
        regex: dis.*
...
```

 While `claim_rules` and its subkeys have special meaning for resweb's processing logic, as they contains the rules that are interpreted to find sites in the site list that match the current user's access token, the other keys are there only to be referenced from the handlebars template, so their name and content is not really relevant to resweb itself. They're used in a loop statement in the handlebars template, like this:

```hbs
<ul>
    {{#each this}}
    <li><a href="{{this.url}}"><span>{{this.name}}</span></a></li>
    {{/each}}
</ul>
```

At the same time, there is a desire to be able to display more data per site than there is available through `name` and `url`

# Proposal #

Instead of having `url` and `name` as fixed keys in elements below `sites`, we could have arbitrary keys that are simply passed through to the handlebars templates.

In order to prevent name collisions with predefined keys like `claim_rules`, we move the set of keys containing arbitrary data below a predefined `data` key. The `url` and `name` keys will still be present in the documentation and predefined templates that are created by the `init-templates` subcommand, but could be changed to something else. And of course, any arbitrary key can be added.

A `resweb.yaml` file would look like this:

```yaml
...
site_list:
  sites:
  - data:
      # all the keys below 'data' are directly available in the 'this'
      # element in the {{each this}} construct in the template 
      name: Disney
      url: https://www.disney.com/
      color:  '#FF5733'
    claim_rules:
    - path: 'realm_access.roles'
      operator: ContainsMatch
      operand:
        regex: dis.*
...
```

A template using the additional `color` key defined here would look like this:

```hbs
<ul>
    {{#each this}}
    <li><a style="color:{{this.color}};" href="{{this.url}}"><span>{{this.name}}</span></a></li>
    {{/each}}
</ul>
```
